### ISSUE TITLE
undefined method `configuration' for RSpec::Mocks:Module (NoMethodError) after upgrading to 0.0.3

### ISSUE THREAD

**Issue by k-rudy** [krisleech/wisper-rspec#21]
Hey,

I've upgraded from 0.0.2 to 0.0.3 and started having this error when running spec suite:

```ruby
/Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-rails-3.4.2/lib/rspec/rails/active_record.rb:11:in `block in initialize_activerecord_configuration': undefined method `configuration' for RSpec::Mocks:Module (NoMethodError)
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:425:in `instance_exec'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:425:in `instance_exec'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:357:in `run'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1724:in `block in run_hooks_with'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1724:in `each'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1724:in `run_hooks_with'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1679:in `with_suite_hooks'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:118:in `block in run_specs'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:77:in `report'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/bin/rspec:23:in `load'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/bin/rspec:23:in `<main>'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/bin/ruby_executable_hooks:15:in `eval'
	from /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/bin/ruby_executable_hooks:15:in `<main>'
```

We're using `mocha` as the mocking backed for our system in `spec_helper.rb`:

```ruby
config.mock_with :mocha
```

Has anyone come across that?

**Comment by krisleech** [comment]
I don't see wisper in the stacktrace.

**Comment by lazyatom** [comment]
Wisper isn't in the stacktrace, but this is indeed triggered by `wisper-rspec`. In `rspec-rails`, if it detects that the `Rspec::Mocks` constant is present, it will attempt to configure it (see https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/active_record.rb#L11-L12). Because `wisper-rspec` loads `rspec/mocks/argument_list_matcher`, we end up in the strange state where the constant does exist, but the rest of `rspec-mocks` (including the `Rspec::Mocks.configuration` method) have not been loaded, and so we get the error above.

**Comment by lazyatom** [comment]
@k-rudy one solution is to explicitly `require 'rspec/mocks'` in your app; that should at least ensure that `rspec-rails` can continue loading.

**Comment by krisleech** [comment]
@lazyatom Thanks for figuring that out.
As far I can understand the problem isn't really directly related to Wisper, it is in assumptions in `rspec-rails`. There is nothing we can do, other than not use `argument_list_matchers`, to solve this?  And we could only be doing that to make another gem work.

If any can see how this could be fixed please reopen the issue.

**Comment by lazyatom** [comment]
I appreciate your perspective, and would agree in the abstract that it's an assumption within spec-rails that triggers the error... but that said, it's going to be _much_ easier to change things in this library than convince RSpec that they should let people load arbitrary bits of their libraries without them making any assumptions. Feel free to chip in here: https://github.com/rspec/rspec-rails/pull/1856

I think the pragmatic fix here would be for `wisper-rspec` to acknowledge the behaviour of `rspec-rails` and sidestep the problem; adding `require "rspec/mocks"` instead of the deep require to `rspec/mocks/argument_list_matches` would prevent anyone from seeing this exception.

**Comment by lazyatom** [comment]
FYI, rspec just merged my change, so this is all resolved now.

**Comment by krisleech** [comment]
@lazyatom Nice one :+1:
